### ISSUE TITLE
62 Frontend bugs

### ISSUE THREAD

**Issue by AniSanikidze** [AgiliaErnis/restaurateur#116]
- The page refresh redirects the user to the home page.
- If the phone number is not available, the phone modal displays just this: "Phone number: "
- Error occurs when the cookie time passes and the user still remains logged in.
- Removing second saved restaurants requires 2 clicks on the remove button and sends a POST request.
- Saving restaurant scrolls to the top of the page.

**Comment by adzai** [comment]
On saved restaurants page, if you start removing restaurants from the top, first restaurant gets removed just fine. When you click on the new top restaurant to be removed it sends a POST request, if you click again it sends the correct DELETE request. This only happens when a new restaurant becomes the top (first) restaurant on that page. You can delete from the bottom just fine.

**Comment by AniSanikidze** [comment]
> On saved restaurants page, if you start removing restaurants from the top, first restaurant gets removed just fine. When you click on the new top restaurant to be removed it sends a POST request, if you click again it sends the correct DELETE request. This only happens when a new restaurant becomes the top (first) restaurant on that page. You can delete from the bottom just fine.

Fixed,#117.
